name: microservice
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0-108.0.dev

# Add regular dependencies here.
dependencies:
  grpc: ^3.1.0
  protobuf: ^2.1.0
  logging: ^1.1.0
  event_bus: ^2.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
