name: hedera_api
description: My new Dart package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies: 
  grpc: ^3.1.0
  protobuf: ^2.1.0
  equatable: ^2.0.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
